kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: frontend-hpa
  namespace: asset-tracker-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 5
  # behavior:
  # scaleUp:
  #   stabilizationWindowSeconds: 10
  #   policies:
  #     - type: Pods
  #       value: 2
  #       periodSeconds: 10



  # kubectl apply -f frontend_hpa.yml
  # kubectl get hpa -n asset-tracker-ns
  # kubectl run -i --tty load-generator --image=busybox -n asset-tracker-ns /bin/sh
  # while true; do wget -q -O- http://frontend-service.asset-tracker-ns.svc.cluster.local; done